"""phase_a_knowledge_base

Revision ID: 32dafb55b4af
Revises: 83eba0dd44dc
Create Date: 2026-08-04 10:52:40.680558

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op
from codelith.db.types import json_column

# revision identifiers, used by Alembic.
revision: str = '32dafb55b4af'
down_revision: str | None = '83eba0dd44dc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_bases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('commit_sha', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('stats_json', json_column(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'commit_sha', name='uq_kb_project_commit')
    )
    op.create_index('ix_kb_project_status', 'knowledge_bases', ['project_id', 'status'], unique=False)
    op.create_index(op.f('ix_knowledge_bases_job_id'), 'knowledge_bases', ['job_id'], unique=False)
    op.create_index(op.f('ix_knowledge_bases_project_id'), 'knowledge_bases', ['project_id'], unique=False)
    op.create_index(op.f('ix_knowledge_bases_status'), 'knowledge_bases', ['status'], unique=False)
    op.create_table('kb_entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kb_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('data_json', json_column(), nullable=False),
    sa.Column('source_path', sa.Text(), nullable=True),
    sa.Column('source_line', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledge_bases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kb_entities_kb_id'), 'kb_entities', ['kb_id'], unique=False)
    op.create_index('ix_kb_entities_kb_kind', 'kb_entities', ['kb_id', 'kind'], unique=False)
    op.create_index('ix_kb_entities_kb_name', 'kb_entities', ['kb_id', 'name'], unique=False)
    op.create_table('kb_modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kb_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('file_count', sa.Integer(), nullable=False),
    sa.Column('loc', sa.Integer(), nullable=False),
    sa.Column('is_test', sa.Boolean(), nullable=False),
    sa.Column('symbols_json', json_column(), nullable=False),
    sa.Column('files_json', json_column(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledge_bases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kb_id', 'path', name='uq_kb_module_path')
    )
    op.create_index(op.f('ix_kb_modules_kb_id'), 'kb_modules', ['kb_id'], unique=False)
    op.create_index('ix_kb_modules_kb_role', 'kb_modules', ['kb_id', 'role'], unique=False)
    op.create_index(op.f('ix_kb_modules_language'), 'kb_modules', ['language'], unique=False)
    op.create_index(op.f('ix_kb_modules_role'), 'kb_modules', ['role'], unique=False)
    op.create_table('kb_narratives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kb_id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=48), nullable=False),
    sa.Column('content_md', sa.Text(), nullable=False),
    sa.Column('source_refs_json', json_column(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledge_bases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kb_id', 'topic', name='uq_kb_narrative_topic')
    )
    op.create_index(op.f('ix_kb_narratives_kb_id'), 'kb_narratives', ['kb_id'], unique=False)
    op.add_column('code_chunks', sa.Column('kb_id', sa.Integer(), nullable=True))
    # NOTE: autogenerate wanted to drop ix_code_chunks_embedding here. That is the
    # pgvector HNSW index created by hand in 0001; SQLAlchemy metadata does not know
    # about it, so every autogenerate will keep proposing the drop. Never accept it.
    op.create_index(op.f('ix_code_chunks_kb_id'), 'code_chunks', ['kb_id'], unique=False)
    op.create_foreign_key(
        'fk_code_chunks_kb_id', 'code_chunks', 'knowledge_bases',
        ['kb_id'], ['id'], ondelete='CASCADE',
    )
    op.add_column('jobs', sa.Column('job_type', sa.String(length=32), server_default='composition', nullable=False))
    op.create_index(op.f('ix_jobs_job_type'), 'jobs', ['job_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_job_type'), table_name='jobs')
    op.drop_column('jobs', 'job_type')
    op.drop_constraint('fk_code_chunks_kb_id', 'code_chunks', type_='foreignkey')
    op.drop_index(op.f('ix_code_chunks_kb_id'), table_name='code_chunks')
    # ix_code_chunks_embedding is intentionally untouched — upgrade() never drops it.
    op.drop_column('code_chunks', 'kb_id')
    op.drop_index(op.f('ix_kb_narratives_kb_id'), table_name='kb_narratives')
    op.drop_table('kb_narratives')
    op.drop_index(op.f('ix_kb_modules_role'), table_name='kb_modules')
    op.drop_index(op.f('ix_kb_modules_language'), table_name='kb_modules')
    op.drop_index('ix_kb_modules_kb_role', table_name='kb_modules')
    op.drop_index(op.f('ix_kb_modules_kb_id'), table_name='kb_modules')
    op.drop_table('kb_modules')
    op.drop_index('ix_kb_entities_kb_name', table_name='kb_entities')
    op.drop_index('ix_kb_entities_kb_kind', table_name='kb_entities')
    op.drop_index(op.f('ix_kb_entities_kb_id'), table_name='kb_entities')
    op.drop_table('kb_entities')
    op.drop_index(op.f('ix_knowledge_bases_status'), table_name='knowledge_bases')
    op.drop_index(op.f('ix_knowledge_bases_project_id'), table_name='knowledge_bases')
    op.drop_index(op.f('ix_knowledge_bases_job_id'), table_name='knowledge_bases')
    op.drop_index('ix_kb_project_status', table_name='knowledge_bases')
    op.drop_table('knowledge_bases')
    # ### end Alembic commands ###
