"""initial schema

One migration, generated from the models.

There were fourteen, and they were shaped by PostgreSQL: `CREATE EXTENSION vector`, a
`vector(n)` column, an HNSW index, and a long tail of `ALTER COLUMN` that SQLite
cannot perform at all. Replaying them was never going to work on the database this
now runs on, and rewriting them in `batch_alter_table` would have been churn on files
that had already done their job.

So the chain was squashed. This is the schema those fourteen were converging on, and
it is the baseline every future migration builds from. The history is in git, which
is where history belongs.

Revision ID: alembic/versions\6b651d17aacd
Revises:
Create Date: 2026-09-02
"""
from collections.abc import Sequence

import sqlalchemy as sa

# The embedding column is a `PackedVector` — float32 bytes. Autogenerate names the
# type but does not import the module that defines it.
import codelith.db.types
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6b651d17aacd'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('plan_tier', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizations_slug'), ['slug'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_org_id'), ['org_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_resource_type'), ['resource_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('oauth_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False),
    sa.Column('access_token', sa.String(length=2048), nullable=True),
    sa.Column('refresh_token', sa.String(length=2048), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('oauth_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oauth_accounts_user_id'), ['user_id'], unique=False)

    op.create_table('org_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('org_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_org_members_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_org_members_user_id'), ['user_id'], unique=False)

    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_slug'), ['slug'], unique=False)

    op.create_table('system_settings',
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('chat_threads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_threads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_threads_project_id'), ['project_id'], unique=False)

    op.create_table('graph_calls',
    sa.Column('src_path', sa.Text(), nullable=False),
    sa.Column('src_qname', sa.Text(), nullable=False),
    sa.Column('dst_path', sa.Text(), nullable=False),
    sa.Column('dst_qname', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('kb_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('graph_calls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_graph_calls_kb_id'), ['kb_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_graph_calls_project_id'), ['project_id'], unique=False)
        batch_op.create_index('ix_graph_calls_scope_dst', ['project_id', 'kb_id', 'dst_qname'], unique=False)

    op.create_table('graph_files',
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('module_key', sa.Text(), nullable=True),
    sa.Column('loc', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('kb_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('graph_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_graph_files_kb_id'), ['kb_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_graph_files_project_id'), ['project_id'], unique=False)
        batch_op.create_index('ix_graph_files_scope_path', ['project_id', 'kb_id', 'path'], unique=False)

    op.create_table('graph_imports',
    sa.Column('src', sa.Text(), nullable=False),
    sa.Column('dst', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('kb_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('graph_imports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_graph_imports_kb_id'), ['kb_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_graph_imports_project_id'), ['project_id'], unique=False)
        batch_op.create_index('ix_graph_imports_scope_dst', ['project_id', 'kb_id', 'dst'], unique=False)
        batch_op.create_index('ix_graph_imports_scope_src', ['project_id', 'kb_id', 'src'], unique=False)

    op.create_table('graph_modules',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('kb_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('graph_modules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_graph_modules_kb_id'), ['kb_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_graph_modules_project_id'), ['project_id'], unique=False)

    op.create_table('graph_packages',
    sa.Column('src', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('kb_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('graph_packages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_graph_packages_kb_id'), ['kb_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_graph_packages_project_id'), ['project_id'], unique=False)

    op.create_table('graph_symbols',
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('qname', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('kind', sa.String(length=50), nullable=True),
    sa.Column('line', sa.Integer(), nullable=True),
    sa.Column('end_line', sa.Integer(), nullable=True),
    sa.Column('visibility', sa.String(length=20), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('kb_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('graph_symbols', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_graph_symbols_kb_id'), ['kb_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_graph_symbols_project_id'), ['project_id'], unique=False)
        batch_op.create_index('ix_graph_symbols_scope_path', ['project_id', 'kb_id', 'path'], unique=False)
        batch_op.create_index('ix_graph_symbols_scope_qname', ['project_id', 'kb_id', 'qname'], unique=False)

    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('job_type', sa.String(length=32), server_default='composition', nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('workflow_run_id', sa.String(length=255), nullable=True),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('scope_json', sa.JSON(), nullable=False),
    sa.Column('resume_state_json', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_job_type'), ['job_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_status'), ['status'], unique=False)

    op.create_table('project_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('url_or_path', sa.Text(), nullable=False),
    sa.Column('branch', sa.String(length=255), nullable=True),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_sources_project_id'), ['project_id'], unique=False)

    op.create_table('agent_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('extra_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_logs_job_id'), ['job_id'], unique=False)

    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('evidence_json', sa.JSON(), nullable=False),
    sa.Column('citations_json', sa.JSON(), nullable=False),
    sa.Column('stripped_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['chat_threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_messages_thread_id'), ['thread_id'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('doc_type', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content_markdown', sa.Text(), nullable=True),
    sa.Column('storage_path', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_project_id'), ['project_id'], unique=False)

    op.create_table('job_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('input_json', sa.JSON(), nullable=False),
    sa.Column('output_json', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_steps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_steps_job_id'), ['job_id'], unique=False)

    op.create_table('knowledge_bases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('commit_sha', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('stats_json', sa.JSON(), nullable=False),
    sa.Column('architecture_json', sa.JSON(), nullable=False),
    sa.Column('site_map_json', sa.JSON(), nullable=False),
    sa.Column('file_hashes_json', sa.JSON(), nullable=False),
    sa.Column('strategy_json', sa.JSON(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'commit_sha', name='uq_kb_project_commit')
    )
    with op.batch_alter_table('knowledge_bases', schema=None) as batch_op:
        batch_op.create_index('ix_kb_project_status', ['project_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_bases_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_bases_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_bases_status'), ['status'], unique=False)

    op.create_table('code_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('kb_id', sa.Integer(), nullable=True),
    sa.Column('source_path', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('chunk_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('start_line', sa.Integer(), nullable=True),
    sa.Column('end_line', sa.Integer(), nullable=True),
    sa.Column('embedding', codelith.db.types.PackedVector(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledge_bases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('code_chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_code_chunks_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_code_chunks_kb_id'), ['kb_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_code_chunks_project_id'), ['project_id'], unique=False)

    op.create_table('doc_sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('nav_json', sa.JSON(), nullable=False),
    sa.Column('kb_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledge_bases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', name='uq_doc_site_project')
    )
    with op.batch_alter_table('doc_sites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_doc_sites_kb_id'), ['kb_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_doc_sites_project_id'), ['project_id'], unique=False)

    op.create_table('document_exports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('format', sa.String(length=50), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_exports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_exports_document_id'), ['document_id'], unique=False)

    op.create_table('kb_entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kb_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('data_json', sa.JSON(), nullable=False),
    sa.Column('source_path', sa.Text(), nullable=True),
    sa.Column('source_line', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledge_bases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kb_entities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kb_entities_kb_id'), ['kb_id'], unique=False)
        batch_op.create_index('ix_kb_entities_kb_kind', ['kb_id', 'kind'], unique=False)
        batch_op.create_index('ix_kb_entities_kb_name', ['kb_id', 'name'], unique=False)

    op.create_table('kb_modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kb_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('file_count', sa.Integer(), nullable=False),
    sa.Column('loc', sa.Integer(), nullable=False),
    sa.Column('is_test', sa.Boolean(), nullable=False),
    sa.Column('symbols_json', sa.JSON(), nullable=False),
    sa.Column('files_json', sa.JSON(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledge_bases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kb_id', 'path', name='uq_kb_module_path')
    )
    with op.batch_alter_table('kb_modules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kb_modules_kb_id'), ['kb_id'], unique=False)
        batch_op.create_index('ix_kb_modules_kb_role', ['kb_id', 'role'], unique=False)
        batch_op.create_index(batch_op.f('ix_kb_modules_language'), ['language'], unique=False)
        batch_op.create_index(batch_op.f('ix_kb_modules_role'), ['role'], unique=False)

    op.create_table('kb_narratives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kb_id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=48), nullable=False),
    sa.Column('content_md', sa.Text(), nullable=False),
    sa.Column('source_refs_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledge_bases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kb_id', 'topic', name='uq_kb_narrative_topic')
    )
    with op.batch_alter_table('kb_narratives', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kb_narratives_kb_id'), ['kb_id'], unique=False)

    op.create_table('doc_site_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('commit_sha', sa.String(length=64), nullable=True),
    sa.Column('nav_json', sa.JSON(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['doc_sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'label', name='uq_doc_site_version_label')
    )
    with op.batch_alter_table('doc_site_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_doc_site_versions_site_id'), ['site_id'], unique=False)

    op.create_table('doc_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('section_slug', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('doc_type', sa.String(length=50), nullable=False),
    sa.Column('intent', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('content_markdown', sa.Text(), nullable=True),
    sa.Column('previous_markdown', sa.Text(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('kb_id', sa.Integer(), nullable=True),
    sa.Column('commit_sha', sa.String(length=64), nullable=True),
    sa.Column('source_files_json', sa.JSON(), nullable=False),
    sa.Column('key_files_json', sa.JSON(), nullable=False),
    sa.Column('grounding_json', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('qa_score', sa.Float(), nullable=True),
    sa.Column('qa_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledge_bases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['doc_sites.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['doc_site_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('doc_pages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_doc_pages_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_doc_pages_kb_id'), ['kb_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_doc_pages_site_id'), ['site_id'], unique=False)
        batch_op.create_index('ix_doc_pages_site_section', ['site_id', 'section_slug'], unique=False)
        batch_op.create_index('ix_doc_pages_site_status', ['site_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_doc_pages_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_doc_pages_version_id'), ['version_id'], unique=False)
        batch_op.create_index('ux_doc_pages_live', ['site_id', 'section_slug', 'slug'], unique=True, sqlite_where=sa.text('version_id IS NULL'))
        batch_op.create_index('ux_doc_pages_versioned', ['site_id', 'version_id', 'section_slug', 'slug'], unique=True, sqlite_where=sa.text('version_id IS NOT NULL'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doc_pages', schema=None) as batch_op:
        batch_op.drop_index('ux_doc_pages_versioned', sqlite_where=sa.text('version_id IS NOT NULL'))
        batch_op.drop_index('ux_doc_pages_live', sqlite_where=sa.text('version_id IS NULL'))
        batch_op.drop_index(batch_op.f('ix_doc_pages_version_id'))
        batch_op.drop_index(batch_op.f('ix_doc_pages_status'))
        batch_op.drop_index('ix_doc_pages_site_status')
        batch_op.drop_index('ix_doc_pages_site_section')
        batch_op.drop_index(batch_op.f('ix_doc_pages_site_id'))
        batch_op.drop_index(batch_op.f('ix_doc_pages_kb_id'))
        batch_op.drop_index(batch_op.f('ix_doc_pages_job_id'))

    op.drop_table('doc_pages')
    with op.batch_alter_table('doc_site_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_doc_site_versions_site_id'))

    op.drop_table('doc_site_versions')
    with op.batch_alter_table('kb_narratives', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kb_narratives_kb_id'))

    op.drop_table('kb_narratives')
    with op.batch_alter_table('kb_modules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kb_modules_role'))
        batch_op.drop_index(batch_op.f('ix_kb_modules_language'))
        batch_op.drop_index('ix_kb_modules_kb_role')
        batch_op.drop_index(batch_op.f('ix_kb_modules_kb_id'))

    op.drop_table('kb_modules')
    with op.batch_alter_table('kb_entities', schema=None) as batch_op:
        batch_op.drop_index('ix_kb_entities_kb_name')
        batch_op.drop_index('ix_kb_entities_kb_kind')
        batch_op.drop_index(batch_op.f('ix_kb_entities_kb_id'))

    op.drop_table('kb_entities')
    with op.batch_alter_table('document_exports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_exports_document_id'))

    op.drop_table('document_exports')
    with op.batch_alter_table('doc_sites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_doc_sites_project_id'))
        batch_op.drop_index(batch_op.f('ix_doc_sites_kb_id'))

    op.drop_table('doc_sites')
    with op.batch_alter_table('code_chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_code_chunks_project_id'))
        batch_op.drop_index(batch_op.f('ix_code_chunks_kb_id'))
        batch_op.drop_index(batch_op.f('ix_code_chunks_job_id'))

    op.drop_table('code_chunks')
    with op.batch_alter_table('knowledge_bases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_bases_status'))
        batch_op.drop_index(batch_op.f('ix_knowledge_bases_project_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_bases_job_id'))
        batch_op.drop_index('ix_kb_project_status')

    op.drop_table('knowledge_bases')
    with op.batch_alter_table('job_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_steps_job_id'))

    op.drop_table('job_steps')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_project_id'))
        batch_op.drop_index(batch_op.f('ix_documents_job_id'))

    op.drop_table('documents')
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_messages_thread_id'))

    op.drop_table('chat_messages')
    with op.batch_alter_table('agent_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_logs_job_id'))

    op.drop_table('agent_logs')
    with op.batch_alter_table('project_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_sources_project_id'))

    op.drop_table('project_sources')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_jobs_project_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_job_type'))

    op.drop_table('jobs')
    with op.batch_alter_table('graph_symbols', schema=None) as batch_op:
        batch_op.drop_index('ix_graph_symbols_scope_qname')
        batch_op.drop_index('ix_graph_symbols_scope_path')
        batch_op.drop_index(batch_op.f('ix_graph_symbols_project_id'))
        batch_op.drop_index(batch_op.f('ix_graph_symbols_kb_id'))

    op.drop_table('graph_symbols')
    with op.batch_alter_table('graph_packages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_graph_packages_project_id'))
        batch_op.drop_index(batch_op.f('ix_graph_packages_kb_id'))

    op.drop_table('graph_packages')
    with op.batch_alter_table('graph_modules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_graph_modules_project_id'))
        batch_op.drop_index(batch_op.f('ix_graph_modules_kb_id'))

    op.drop_table('graph_modules')
    with op.batch_alter_table('graph_imports', schema=None) as batch_op:
        batch_op.drop_index('ix_graph_imports_scope_src')
        batch_op.drop_index('ix_graph_imports_scope_dst')
        batch_op.drop_index(batch_op.f('ix_graph_imports_project_id'))
        batch_op.drop_index(batch_op.f('ix_graph_imports_kb_id'))

    op.drop_table('graph_imports')
    with op.batch_alter_table('graph_files', schema=None) as batch_op:
        batch_op.drop_index('ix_graph_files_scope_path')
        batch_op.drop_index(batch_op.f('ix_graph_files_project_id'))
        batch_op.drop_index(batch_op.f('ix_graph_files_kb_id'))

    op.drop_table('graph_files')
    with op.batch_alter_table('graph_calls', schema=None) as batch_op:
        batch_op.drop_index('ix_graph_calls_scope_dst')
        batch_op.drop_index(batch_op.f('ix_graph_calls_project_id'))
        batch_op.drop_index(batch_op.f('ix_graph_calls_kb_id'))

    op.drop_table('graph_calls')
    with op.batch_alter_table('chat_threads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_threads_project_id'))

    op.drop_table('chat_threads')
    op.drop_table('system_settings')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_slug'))
        batch_op.drop_index(batch_op.f('ix_projects_org_id'))

    op.drop_table('projects')
    with op.batch_alter_table('org_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_org_members_user_id'))
        batch_op.drop_index(batch_op.f('ix_org_members_org_id'))

    op.drop_table('org_members')
    with op.batch_alter_table('oauth_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oauth_accounts_user_id'))

    op.drop_table('oauth_accounts')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_resource_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_org_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_slug'))

    op.drop_table('organizations')
    # ### end Alembic commands ###
