"""model registry: configured endpoints and tier assignments

Written by hand rather than autogenerated. Autogenerate compares the models against
whatever database `DATABASE_URL` points at, and on this machine that is a real one
carrying real projects — it would have folded in any unrelated drift it happened to
find alongside the two tables this change is actually about.

Moves model configuration out of `.env` and into the database, so an installation
somebody runs as an application can be configured from its own settings page rather
than by editing a file inside a container and restarting it.

Revision ID: a1c4e77b2f10
Revises: 6b651d17aacd
"""

from __future__ import annotations

import sqlalchemy as sa

from alembic import op

revision: str = "a1c4e77b2f10"
down_revision: str | None = "6b651d17aacd"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "model_configs",
        sa.Column("id", sa.Integer(), nullable=False),
        # The label is how a person picks one out of a dropdown, so two sharing one
        # is a menu you cannot choose from.
        sa.Column("label", sa.String(length=120), nullable=False),
        # openai | anthropic | local. Decides which of the columns below matter.
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("model", sa.String(length=200), nullable=False),
        # `local` only: the hosted providers have a fixed endpoint, and making that
        # settable is how an API key once ended up posted to a server on localhost.
        sa.Column("base_url", sa.Text(), nullable=True),
        sa.Column("context_window", sa.Integer(), nullable=True),
        # Fernet, keyed off APP_SECRET_KEY. Never returned by the API.
        sa.Column("api_key_encrypted", sa.Text(), nullable=True),
        sa.Column("last_test_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("label", name="uq_model_config_label"),
    )

    op.create_table(
        "tier_assignments",
        # The tier is the key: "switch the writing model" is an update, never a
        # second row.
        sa.Column("tier", sa.String(length=32), nullable=False),
        sa.Column("model_config_id", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        # RESTRICT, not CASCADE: deleting a model a tier is using would leave that
        # tier pointing at nothing, and the first sign would be a failed job.
        sa.ForeignKeyConstraint(
            ["model_config_id"], ["model_configs.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("tier"),
    )
    op.create_index(
        "ix_tier_assignments_model_config_id", "tier_assignments", ["model_config_id"]
    )


def downgrade() -> None:
    op.drop_index("ix_tier_assignments_model_config_id", table_name="tier_assignments")
    op.drop_table("tier_assignments")
    op.drop_table("model_configs")
