"""doc_site_versions

Phase S6 — frozen snapshots of a documentation site.

A version's pages are ordinary `doc_pages` rows carrying its `version_id`, so a
reader and an export walk the same code whether they are looking at the live site or
at "v1.2". `version_id IS NULL` is the live site: the one that gets written, marked
stale, and read by default.

That is why `uq_doc_page_slug` becomes two **partial** unique indexes. A NULL does
not compare equal to itself in SQL, so a single
`UNIQUE(site_id, version_id, section_slug, slug)` would silently permit two live
pages on the same slug — the one thing the whole design forbids.

Written by hand rather than autogenerated: `alembic revision --autogenerate` proposes
dropping `ix_code_chunks_embedding` on every run, because the pgvector HNSW index was
created by raw SQL in 0001 and is invisible to SQLAlchemy metadata.

Revision ID: a91b6d47c052
Revises: f5c93a1e0b28
Create Date: 2026-08-06
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op
from codelith.db.types import json_column

revision: str = "a91b6d47c052"
down_revision: str | None = "f5c93a1e0b28"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "doc_site_versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("site_id", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=100), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("commit_sha", sa.String(length=64), nullable=True),
        sa.Column(
            "nav_json",
            json_column(),
            nullable=False,
            server_default="[]",
        ),
        sa.Column("page_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("snapshot_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["site_id"], ["doc_sites.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("site_id", "label", name="uq_doc_site_version_label"),
    )
    op.create_index(
        op.f("ix_doc_site_versions_site_id"), "doc_site_versions", ["site_id"]
    )

    op.add_column("doc_pages", sa.Column("version_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        "fk_doc_pages_version",
        "doc_pages",
        "doc_site_versions",
        ["version_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_index(op.f("ix_doc_pages_version_id"), "doc_pages", ["version_id"])

    op.drop_constraint("uq_doc_page_slug", "doc_pages", type_="unique")
    op.create_index(
        "ux_doc_pages_live",
        "doc_pages",
        ["site_id", "section_slug", "slug"],
        unique=True,
        postgresql_where=sa.text("version_id IS NULL"),
    )
    op.create_index(
        "ux_doc_pages_versioned",
        "doc_pages",
        ["site_id", "version_id", "section_slug", "slug"],
        unique=True,
        postgresql_where=sa.text("version_id IS NOT NULL"),
    )


def downgrade() -> None:
    op.drop_index("ux_doc_pages_versioned", table_name="doc_pages")
    op.drop_index("ux_doc_pages_live", table_name="doc_pages")
    # Snapshot pages would violate the restored constraint; they only exist because
    # versions do, so they go with them.
    op.execute("DELETE FROM doc_pages WHERE version_id IS NOT NULL")
    op.create_unique_constraint(
        "uq_doc_page_slug", "doc_pages", ["site_id", "section_slug", "slug"]
    )

    op.drop_index(op.f("ix_doc_pages_version_id"), table_name="doc_pages")
    op.drop_constraint("fk_doc_pages_version", "doc_pages", type_="foreignkey")
    op.drop_column("doc_pages", "version_id")

    op.drop_index(op.f("ix_doc_site_versions_site_id"), table_name="doc_site_versions")
    op.drop_table("doc_site_versions")
