"""kb_architecture_json

Persist the synthesised architecture map on the knowledge base.

Analysis produced the map, `narrative_writer` read it, and it was then discarded with
the workflow state. Composition therefore had no way to reach it: `DiagramAgent` read
`state.get("architecture_map", {})` from a `CompositionState` that never carried the
key, so every diagram in the two-phase pipeline was drawn from "(no services
identified)" and invented its own components.

Written by hand rather than autogenerated: `alembic revision --autogenerate` proposes
dropping `ix_code_chunks_embedding` on every run, because the pgvector HNSW index was
created by raw SQL in 0001 and is invisible to SQLAlchemy metadata.

Revision ID: b7c41a9f2e10
Revises: 32dafb55b4af
Create Date: 2026-08-06
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op
from codelith.db.types import json_column

revision: str = "b7c41a9f2e10"
down_revision: str | None = "32dafb55b4af"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column(
        "knowledge_bases",
        sa.Column(
            "architecture_json",
            json_column(),
            nullable=False,
            server_default="{}",
        ),
    )


def downgrade() -> None:
    op.drop_column("knowledge_bases", "architecture_json")
