"""doc_sites_and_pages

Phase S1 — the schema behind one documentation site per project, grown a section at
a time, instead of one flat document per composition job.

Three things land together because they are one idea:

  * `doc_sites` — the site and its ordered nav, one row per project.
  * `doc_pages` — the pages. `(site_id, section_slug, slug)` is unique because the
    slug is a URL: it is assigned once from the first title and pinned forever, and
    the merge in `SiteService` matches on it.
  * `knowledge_bases.site_map_json` — the *proposal* from analysis, stored beside
    `architecture_json`. Rebuilt every analysis; never the source of truth for what
    exists.

Written by hand rather than autogenerated: `alembic revision --autogenerate`
proposes dropping `ix_code_chunks_embedding` on every run, because the pgvector HNSW
index was created by raw SQL in 0001 and is invisible to SQLAlchemy metadata.

Revision ID: c3f1d0a7b592
Revises: b7c41a9f2e10
Create Date: 2026-08-06
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "c3f1d0a7b592"
down_revision: str | None = "b7c41a9f2e10"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column(
        "knowledge_bases",
        sa.Column(
            "site_map_json",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default="{}",
        ),
    )

    op.create_table(
        "doc_sites",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column(
            "nav_json",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default="[]",
        ),
        sa.Column("kb_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["kb_id"], ["knowledge_bases.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", name="uq_doc_site_project"),
    )
    op.create_index(op.f("ix_doc_sites_project_id"), "doc_sites", ["project_id"])
    op.create_index(op.f("ix_doc_sites_kb_id"), "doc_sites", ["kb_id"])

    op.create_table(
        "doc_pages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("site_id", sa.Integer(), nullable=False),
        sa.Column("section_slug", sa.String(length=100), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("doc_type", sa.String(length=50), nullable=False),
        sa.Column("intent", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("pinned", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("content_markdown", sa.Text(), nullable=True),
        sa.Column("word_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("job_id", sa.Integer(), nullable=True),
        sa.Column("kb_id", sa.Integer(), nullable=True),
        sa.Column("commit_sha", sa.String(length=64), nullable=True),
        sa.Column(
            "source_files_json",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default="[]",
        ),
        sa.Column(
            "key_files_json",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default="[]",
        ),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["kb_id"], ["knowledge_bases.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["site_id"], ["doc_sites.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("site_id", "section_slug", "slug", name="uq_doc_page_slug"),
    )
    op.create_index(op.f("ix_doc_pages_site_id"), "doc_pages", ["site_id"])
    op.create_index(op.f("ix_doc_pages_status"), "doc_pages", ["status"])
    op.create_index(op.f("ix_doc_pages_job_id"), "doc_pages", ["job_id"])
    op.create_index(op.f("ix_doc_pages_kb_id"), "doc_pages", ["kb_id"])
    op.create_index("ix_doc_pages_site_status", "doc_pages", ["site_id", "status"])
    op.create_index("ix_doc_pages_site_section", "doc_pages", ["site_id", "section_slug"])


def downgrade() -> None:
    op.drop_index("ix_doc_pages_site_section", table_name="doc_pages")
    op.drop_index("ix_doc_pages_site_status", table_name="doc_pages")
    op.drop_index(op.f("ix_doc_pages_kb_id"), table_name="doc_pages")
    op.drop_index(op.f("ix_doc_pages_job_id"), table_name="doc_pages")
    op.drop_index(op.f("ix_doc_pages_status"), table_name="doc_pages")
    op.drop_index(op.f("ix_doc_pages_site_id"), table_name="doc_pages")
    op.drop_table("doc_pages")

    op.drop_index(op.f("ix_doc_sites_kb_id"), table_name="doc_sites")
    op.drop_index(op.f("ix_doc_sites_project_id"), table_name="doc_sites")
    op.drop_table("doc_sites")

    op.drop_column("knowledge_bases", "site_map_json")
