"""job_scope_json

Phase S4 — what a job was *asked* to do, in the reader's vocabulary.

The job list could only say "composition completed". `config_json` holds the
resolved page slugs, but they are pipeline vocabulary; this records the reader's:
which sections, how many pages, and the labels to print. Set at creation, so it is
there before a page exists and survives a job that failed — neither of which
`doc_pages.job_id` alone gives you.

Written by hand rather than autogenerated: `alembic revision --autogenerate` proposes
dropping `ix_code_chunks_embedding` on every run, because the pgvector HNSW index was
created by raw SQL in 0001 and is invisible to SQLAlchemy metadata.

Revision ID: e7a2b4c81d33
Revises: c3f1d0a7b592
Create Date: 2026-08-06
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "e7a2b4c81d33"
down_revision: str | None = "c3f1d0a7b592"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column(
        "jobs",
        sa.Column("scope_json", sa.JSON(), nullable=False, server_default="{}"),
    )


def downgrade() -> None:
    op.drop_column("jobs", "scope_json")
