"""page_staleness_and_qa

Phase S5 — the bookkeeping that makes generated documentation auditable.

Three columns, three claims the product can now make:

  * `knowledge_bases.file_hashes_json` — path → content digest for every file a
    build read. Diffed against the next build to mark *exactly* the pages a change
    invalidated. Deliberately not a git diff: uploads and local directories have no
    commits, and a digest map works for all of them.
  * `doc_pages.previous_markdown` — what a page said before its last rewrite, so a
    regeneration can be reviewed as a diff rather than as a fresh blob.
  * `doc_pages.qa_score` / `qa_json` — QA's verdict per page. One score for a
    twenty-page document was decorative; per page it names what to look at.

Written by hand rather than autogenerated: `alembic revision --autogenerate` proposes
dropping `ix_code_chunks_embedding` on every run, because the pgvector HNSW index was
created by raw SQL in 0001 and is invisible to SQLAlchemy metadata.

Revision ID: f5c93a1e0b28
Revises: e7a2b4c81d33
Create Date: 2026-08-06
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op
from codelith.db.types import json_column

revision: str = "f5c93a1e0b28"
down_revision: str | None = "e7a2b4c81d33"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column(
        "knowledge_bases",
        sa.Column(
            "file_hashes_json",
            json_column(),
            nullable=False,
            server_default="{}",
        ),
    )
    op.add_column("doc_pages", sa.Column("previous_markdown", sa.Text(), nullable=True))
    op.add_column("doc_pages", sa.Column("qa_score", sa.Float(), nullable=True))
    op.add_column(
        "doc_pages",
        sa.Column(
            "qa_json",
            json_column(),
            nullable=False,
            server_default="{}",
        ),
    )


def downgrade() -> None:
    op.drop_column("doc_pages", "qa_json")
    op.drop_column("doc_pages", "qa_score")
    op.drop_column("doc_pages", "previous_markdown")
    op.drop_column("knowledge_bases", "file_hashes_json")
