"""
Getting a solo database to head without replaying six months of history.

Server mode migrates: there are deployments with data in them, and Alembic is how the
schema moves forward without losing it. Solo mode has no such history. The database is
created on the machine that will use it, at whatever the current schema is, and there
is nothing to migrate *through*.

That distinction matters because the chain cannot be replayed on SQLite anyway. Its
`ALTER TABLE` does not do `SET NOT NULL`, or change a column type, or drop a
constraint — the operations a year of migrations is mostly made of. Rewriting thirteen
migrations in `batch_alter_table` to support a database none of them has ever run on
would be a lot of churn on files that work, for a path that does not need them.

So: build from the models, then stamp the chain as applied. The schema is identical —
the models are what the migrations have been converging on — and the version table
says `head`, so the *next* migration applies normally.

**The rule that keeps this true:** a migration written from here on must run on SQLite.
`render_as_batch` in `alembic/env.py` makes autogenerated ones do so; a hand-written
`op.execute` of Postgres SQL must ask `codelith.db.migrations.is_postgres()` first.
"""

from __future__ import annotations

import structlog
from sqlalchemy.ext.asyncio import AsyncEngine

logger = structlog.get_logger(__name__)


def _alembic_config(url: str):
    from alembic.config import Config

    cfg = Config("alembic.ini")
    cfg.set_main_option("sqlalchemy.url", url)
    # `alembic/env.py` overrides the URL from settings unless told not to. Without
    # this flag a stamp aimed at a solo database lands on the configured Postgres.
    cfg.attributes["url_set_by_caller"] = True
    return cfg


async def ensure_schema(engine: AsyncEngine) -> bool:
    """
    Make sure the bound database has the current schema. Returns whether it built one.

    A no-op on PostgreSQL: there, Alembic owns the schema and running `create_all`
    behind its back would produce tables the version table does not know about.
    """
    if engine.dialect.name == "postgresql":
        return False

    from sqlalchemy import inspect

    import codelith.models  # noqa: F401  — registers every table on the metadata
    from codelith.db.base import Base

    def _has_tables(conn) -> bool:
        return bool(inspect(conn).get_table_names())

    async with engine.begin() as conn:
        if await conn.run_sync(_has_tables):
            return False
        await conn.run_sync(Base.metadata.create_all)

    # Stamp *after* creating, and only when we created: stamping a database somebody
    # else built would claim migrations ran that never did.
    #
    # Off-thread because `command.stamp` loads `alembic/env.py`, which calls
    # `asyncio.run()` — and this function is already inside a loop. A thread gets its
    # own, which is the whole fix.
    import asyncio

    from alembic import command

    url = str(engine.url.render_as_string(hide_password=False))
    await asyncio.to_thread(command.stamp, _alembic_config(url), "head")

    logger.info(
        "schema_created",
        dialect=engine.dialect.name,
        tables=len(Base.metadata.tables),
    )
    return True
