from __future__ import annotations

import io
import json
import zipfile

from app.models.document import Document


_SIDEBAR_POSITION = {
    "architecture": 1,
    "api": 2,
    "module": 3,
    "tutorial": 4,
    "runbook": 5,
}


class DocusaurusFormatter:
    """
    Produces a ZIP with a Docusaurus-compatible docs directory:
      docusaurus.config.js  (minimal scaffold)
      docs/{doc_type}.mdx   (one per document with frontmatter)
    """

    def format_site(self, docs: list[Document], project_name: str) -> bytes:
        buf = io.BytesIO()
        safe_name = project_name.lower().replace(" ", "-")

        with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
            for doc in docs:
                filename = f"{doc.doc_type}.mdx"
                content = self._mdx_content(doc)
                zf.writestr(f"docs/{filename}", content)

            zf.writestr("docs/intro.mdx", self._intro(project_name))
            zf.writestr("docusaurus.config.js", self._config_js(project_name, safe_name))
            zf.writestr("sidebars.js", self._sidebars_js(docs))

        return buf.getvalue()

    def _mdx_content(self, doc: Document) -> str:
        pos = _SIDEBAR_POSITION.get(doc.doc_type, 10)
        lines = [
            "---",
            f"title: \"{doc.title}\"",
            f"sidebar_label: \"{doc.doc_type.title()}\"",
            f"sidebar_position: {pos}",
            "---",
            "",
            doc.content_markdown or "*No content generated.*",
        ]
        return "\n".join(lines)

    def _intro(self, project_name: str) -> str:
        return (
            "---\ntitle: Introduction\nsidebar_position: 0\n---\n\n"
            f"# {project_name}\n\nWelcome to the generated documentation.\n"
        )

    def _config_js(self, project_name: str, safe_name: str) -> str:
        return f"""\
// @ts-check
const config = {{
  title: '{project_name}',
  tagline: 'Generated by document-anything',
  url: 'https://example.com',
  baseUrl: '/',
  organizationName: 'your-org',
  projectName: '{safe_name}',
  presets: [['classic', {{ docs: {{ sidebarPath: require.resolve('./sidebars.js') }} }} ]],
}};
module.exports = config;
"""

    def _sidebars_js(self, docs: list[Document]) -> str:
        items = json.dumps(["intro"] + [d.doc_type for d in docs], indent=2)
        return f"module.exports = {{ tutorialSidebar: {items} }};\n"
