"""
The site as a Docusaurus project.

Not a docs folder — a project. What this produced before was `docs/`, a config and a
sidebar, which is the interesting half and unrunnable on its own: no `package.json`,
so `npm install` has nothing to read and `npm run start` does not exist. Somebody
comparing it against `npx create-docusaurus` found exactly that.

So the archive now carries everything `create-docusaurus` does that a docs site needs,
and three decisions that a scaffold generated from prose has to make and the default
template does not.

**The blog is off.** The classic preset enables it unless told otherwise and then
fails the build looking for a `blog/` directory that was never written. Nobody
exporting documentation from a codebase wants a blog.

**Docs are the site.** `routeBasePath: '/'` with `slug: /` on the introduction, so
the front page is the documentation rather than a template landing page nobody asked
for. The alternative is shipping a React home page that has to be deleted.

**Pages are `.md`, not `.mdx`, with `markdown.format: 'detect'`.** MDX treats `{` as
an expression and `<` as a component, and this prose is written by a model reading
source code, so it is full of both. As `.mdx` a build fails on the first `{config}` in
a sentence. `detect` parses `.md` as CommonMark and leaves `.mdx` alone, which is the
difference between an export that builds and one that argues.
"""

from __future__ import annotations

import io
import json
import zipfile

from codelith.apps.documentation.formatters.site_tree import (
    SiteTree,
    rewrite_links,
    slugify_filename,
)
from codelith.models.document import Document

#: Pinned to what `create-docusaurus` installs today. A caret rather than an exact
#: version so a lockfile-less install still resolves, and no `@docusaurus/faster`,
#: which is an opt-in build accelerator this does not need.
_DOCUSAURUS = "^3.10.2"

_SIDEBAR_POSITION = {
    "architecture": 1,
    "api": 2,
    "module": 3,
    "tutorial": 4,
    "runbook": 5,
}


class DocusaurusFormatter:
    """
    Produces a ZIP with a Docusaurus-compatible docs directory:
      docusaurus.config.js  (minimal scaffold)
      docs/{doc_type}.mdx   (one per document with frontmatter)
    """

    def format_site(self, docs: list[Document], project_name: str) -> bytes:
        buf = io.BytesIO()
        safe_name = project_name.lower().replace(" ", "-")

        with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
            for doc in docs:
                filename = f"{doc.doc_type}.md"
                content = self._mdx_content(doc)
                zf.writestr(f"docs/{filename}", content)

            zf.writestr("docs/intro.md", self._intro(project_name))
            zf.writestr("docusaurus.config.js", self._config_js(project_name, safe_name))
            zf.writestr("sidebars.js", self._sidebars_js(docs))
            self._scaffold(zf, project_name, safe_name)

        return buf.getvalue()

    def _mdx_content(self, doc: Document) -> str:
        pos = _SIDEBAR_POSITION.get(doc.doc_type, 10)
        lines = [
            "---",
            f"title: \"{doc.title}\"",
            f"sidebar_label: \"{doc.doc_type.title()}\"",
            f"sidebar_position: {pos}",
            "---",
            "",
            doc.content_markdown or "*No content generated.*",
        ]
        return "\n".join(lines)

    def _intro(self, project_name: str) -> str:
        # `slug: /` because docs are served at the root, so this is the front page.
        return (
            "---\ntitle: Introduction\nsidebar_position: 0\nslug: /\n---\n\n"
            f"# {project_name}\n\nWelcome to the generated documentation.\n"
        )

    def _config_js(self, project_name: str, safe_name: str) -> str:
        """
        A config that builds. See the module docstring for the three decisions.

        `onBrokenLinks` warns rather than throws: pages are written from source by a
        model and cite each other, and a single link to a page that was planned but
        never composed should not stop somebody seeing the rest of the site.
        """
        title = project_name.replace("'", "\\'")
        return f"""\
// @ts-check
// Generated by Codelith. Safe to edit — nothing regenerates this file in place.

/** @type {{import('@docusaurus/types').Config}} */
const config = {{
  title: '{title}',
  tagline: 'Written from the codebase by Codelith',
  url: 'https://example.com',
  baseUrl: '/',
  organizationName: 'your-org',
  projectName: '{safe_name}',

  // Warn rather than throw: a page may cite one that was planned and never written.
  onBrokenLinks: 'warn',

  i18n: {{ defaultLocale: 'en', locales: ['en'] }},

  markdown: {{
    // `.md` is CommonMark, `.mdx` is MDX. Without this every `{{` and `<` in prose
    // written from source code is parsed as an expression or a component.
    format: 'detect',
    // Under `markdown.hooks`, not at the top level: the top-level option still works
    // and prints a deprecation warning on every build, which an export should not.
    hooks: {{ onBrokenMarkdownLinks: 'warn' }},
  }},

  presets: [
    [
      'classic',
      /** @type {{import('@docusaurus/preset-classic').Options}} */
      ({{
        docs: {{
          sidebarPath: require.resolve('./sidebars.js'),
          // The documentation is the site. Without this the root is a landing page
          // that does not exist, and every reader lands on a 404.
          routeBasePath: '/',
        }},
        // No blog directory is written, and the classic preset fails looking for one.
        blog: false,
        theme: {{ customCss: require.resolve('./src/css/custom.css') }},
      }}),
    ],
  ],

  themeConfig: {{
    navbar: {{
      title: '{title}',
      items: [
        {{ type: 'docSidebar', sidebarId: 'tutorialSidebar', position: 'left', label: 'Docs' }},
      ],
    }},
    footer: {{
      style: 'dark',
      copyright: 'Written from the code by Codelith.',
    }},
  }},
}};

module.exports = config;
"""

    def _sidebars_js(self, docs: list[Document]) -> str:
        items = json.dumps(["intro"] + [d.doc_type for d in docs], indent=2)
        return f"module.exports = {{ tutorialSidebar: {items} }};\n"


    # ── The project around the docs ───────────────────────────────────────────

    def _scaffold(self, zf: zipfile.ZipFile, title: str, safe_name: str) -> None:
        """
        Everything `npm install && npm run start` needs and `docs/` is not.

        Written once here rather than at each call site, because an export that is
        missing any one of these is an export that cannot be run, and that is not a
        difference a reader would spot in a file listing.
        """
        zf.writestr("package.json", self._package_json(safe_name))
        zf.writestr("README.md", self._readme(title))
        zf.writestr(".gitignore", _GITIGNORE)
        # Referenced by `theme.customCss`; the build fails on a missing one.
        zf.writestr("src/css/custom.css", _CUSTOM_CSS)
        # Docusaurus expects the directory to exist even when it is empty.
        zf.writestr("static/.gitkeep", "")

    @staticmethod
    def _package_json(safe_name: str) -> str:
        return json.dumps(
            {
                "name": safe_name or "docs",
                "version": "0.0.0",
                "private": True,
                "scripts": {
                    "docusaurus": "docusaurus",
                    "start": "docusaurus start",
                    "build": "docusaurus build",
                    "serve": "docusaurus serve",
                    "clear": "docusaurus clear",
                    "deploy": "docusaurus deploy",
                },
                "dependencies": {
                    "@docusaurus/core": _DOCUSAURUS,
                    "@docusaurus/preset-classic": _DOCUSAURUS,
                    "@mdx-js/react": "^3.0.0",
                    "clsx": "^2.0.0",
                    "prism-react-renderer": "^2.3.0",
                    "react": "^19.0.0",
                    "react-dom": "^19.0.0",
                },
                "devDependencies": {"@docusaurus/module-type-aliases": _DOCUSAURUS},
                "browserslist": {
                    "production": [">0.5%", "not dead", "not op_mini all"],
                    "development": [
                        "last 3 chrome version",
                        "last 3 firefox version",
                        "last 5 safari version",
                    ],
                },
                "engines": {"node": ">=20.0"},
            },
            indent=2,
        ) + "\n"

    @staticmethod
    def _readme(title: str) -> str:
        return (
            f"# {title}\n\n"
            "Documentation written from the codebase by "
            "[Codelith](https://github.com/NaumanHSA/codelith), as a Docusaurus site.\n\n"
            "## Running it\n\n"
            "```bash\n"
            "npm install\n"
            "npm run start\n"
            "```\n\n"
            "That serves the site at http://localhost:3000 with live reload.\n\n"
            "## Building it\n\n"
            "```bash\n"
            "npm run build      # static files in build/\n"
            "npm run serve      # preview the built site\n"
            "```\n\n"
            "## What is here\n\n"
            "| Path | What it is |\n"
            "| --- | --- |\n"
            "| `docs/` | The pages, one Markdown file each, in section folders |\n"
            "| `sidebars.js` | The navigation, in the order the site was written in |\n"
            "| `docusaurus.config.js` | Site config. The blog is off and docs are served at `/` |\n"
            "| `src/css/custom.css` | Yours to change |\n\n"
            "Pages are `.md` and the config sets `markdown.format: 'detect'`, so they are\n"
            "parsed as CommonMark. Renaming one to `.mdx` opts it into MDX, where `{` and\n"
            "`<` become expressions and components.\n\n"
            "Requires Node 20 or newer.\n"
        )

    # ── Site tree ─────────────────────────────────────────────────────────────

    def format_site_tree(self, tree: SiteTree) -> bytes:
        """
        A directory per section with a `_category_.json`, and a generated sidebar.

        Docusaurus derives its own ordering from `_category_.json` and
        `sidebar_position`, so the sidebar mirrors the site's nav order exactly
        rather than the alphabetical order it would otherwise invent.
        """
        buf = io.BytesIO()
        safe_name = tree.title.lower().replace(" ", "-")

        with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
            sidebar: list[object] = ["intro"]

            for index, section in enumerate(tree.sections, start=1):
                written = [p for p in section.pages if p.content_markdown.strip()]
                if not written:
                    continue
                folder = slugify_filename(section.slug)
                zf.writestr(
                    f"docs/{folder}/_category_.json",
                    json.dumps({"label": section.title, "position": index}, indent=2),
                )
                ids: list[str] = []
                for position, page in enumerate(written, start=1):
                    name = slugify_filename(page.slug)
                    ids.append(f"{folder}/{name}")
                    zf.writestr(
                        f"docs/{folder}/{name}.md",
                        "---\n"
                        f'title: "{page.title}"\n'
                        f'sidebar_label: "{page.title}"\n'
                        f"sidebar_position: {position}\n"
                        "---\n\n"
                        + rewrite_links(
                            page.content_markdown,
                            from_page=page.address,
                            suffix="",
                            present=tree.addresses,
                        ),
                    )
                sidebar.append({"type": "category", "label": section.title, "items": ids})

            zf.writestr("docs/intro.md", self._tree_intro(tree))
            zf.writestr("docusaurus.config.js", self._config_js(tree.title, safe_name))
            self._scaffold(zf, tree.title, safe_name)
            zf.writestr(
                "sidebars.js",
                f"module.exports = {{ tutorialSidebar: {json.dumps(sidebar, indent=2)} }};\n",
            )
        return buf.getvalue()

    @staticmethod
    def _tree_intro(tree: SiteTree) -> str:
        body = tree.home_markdown or "Generated documentation."
        return (
            "---\ntitle: Introduction\nsidebar_position: 0\nslug: /\n---\n\n"
            f"# {tree.title}\n\n{body}\n"
        )


_GITIGNORE = """# Dependencies
/node_modules

# Production
/build

# Generated
.docusaurus
.cache-loader

# Misc
.DS_Store
.env.local
npm-debug.log*
"""

_CUSTOM_CSS = """/* Yours to change. Codelith writes the pages, not the look.
   Docusaurus's own variables are documented at
   https://docusaurus.io/docs/styling-layout */
:root {
  --ifm-color-primary: #c2400c;
  --ifm-color-primary-dark: #af3a0b;
  --ifm-color-primary-darker: #a5360a;
  --ifm-color-primary-darkest: #882d08;
  --ifm-color-primary-light: #d5460d;
  --ifm-color-primary-lighter: #e14a0e;
  --ifm-color-primary-lightest: #f15a1d;
  --ifm-code-font-size: 92%;
}

[data-theme='dark'] {
  --ifm-color-primary: #ff8a5c;
  --ifm-color-primary-dark: #ff7238;
  --ifm-color-primary-darker: #ff6626;
  --ifm-color-primary-darkest: #ee4900;
  --ifm-color-primary-light: #ffa280;
  --ifm-color-primary-lighter: #ffae92;
  --ifm-color-primary-lightest: #ffd2c6;
}
"""
